import { GAME_HEIGHT } from '../config';

export const SCENE_ALIGNMENT_Y_OFFSET = -36;
export const PLAYER_ANCHOR_Y = GAME_HEIGHT - 82;
export const LANE_WORLD_SPACING_AT_NEAR = 224;
export const MAIN_ROAD_EDGE_LANE_OFFSET = 1.5;
export const ROAD_BUFFER_LANE_OFFSET = 1 / 3;
export const OUTER_ROAD_EDGE_LANE_OFFSET = MAIN_ROAD_EDGE_LANE_OFFSET + ROAD_BUFFER_LANE_OFFSET;
export const ROADSIDE_LAMP_LANE_OFFSET = OUTER_ROAD_EDGE_LANE_OFFSET;
export const TRACK_BOTTOM_EDGE_MULTIPLIER = OUTER_ROAD_EDGE_LANE_OFFSET;
export const TRACK_ENDPOINT_WIDTH_PROGRESS = 0.014;
export const TRACK_VISUAL_HORIZON_PROGRESS = TRACK_ENDPOINT_WIDTH_PROGRESS;
export const PROJECTED_NEAR_SCALE = 2.28;
export const ITEM_VISUAL_SCALE = 1.2;
export const ITEM_GROUND_SHADOW_ALPHA = 0.22;

export const BASE_TRACK_HORIZON_Y = Math.round(GAME_HEIGHT * 0.5);
export const BASE_CITY_BACKGROUND_Y_OFFSET = -24;
export const BASE_SUNSET_BACKGROUND_Y_OFFSET = 0;
export const TRACK_ENDPOINT_Y_OFFSET = -20;

export const TRACK_HORIZON_Y = BASE_TRACK_HORIZON_Y + SCENE_ALIGNMENT_Y_OFFSET + TRACK_ENDPOINT_Y_OFFSET;
export const CITY_BACKGROUND_Y_OFFSET = BASE_CITY_BACKGROUND_Y_OFFSET + SCENE_ALIGNMENT_Y_OFFSET;
export const SUNSET_BACKGROUND_Y_OFFSET = BASE_SUNSET_BACKGROUND_Y_OFFSET + SCENE_ALIGNMENT_Y_OFFSET;
