import { GAME_HEIGHT } from '../config';

export const SCENE_ALIGNMENT_Y_OFFSET = -36;

export const BASE_TRACK_HORIZON_Y = Math.round(GAME_HEIGHT * 0.5);
export const BASE_CITY_BACKGROUND_Y_OFFSET = -24;
export const BASE_SUNSET_BACKGROUND_Y_OFFSET = 0;

export const TRACK_HORIZON_Y = BASE_TRACK_HORIZON_Y + SCENE_ALIGNMENT_Y_OFFSET;
export const CITY_BACKGROUND_Y_OFFSET = BASE_CITY_BACKGROUND_Y_OFFSET + SCENE_ALIGNMENT_Y_OFFSET;
export const SUNSET_BACKGROUND_Y_OFFSET = BASE_SUNSET_BACKGROUND_Y_OFFSET + SCENE_ALIGNMENT_Y_OFFSET;
